name: CI

on:
  pull_request: ~
  push:
    branches: ['main']
  schedule:
    - cron: '0 */12 * * *'

jobs:
  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Validate composer.json
        run: composer validate --strict
  cs:
    name: Check coding standards
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            tools: php-cs-fixer
        - name: Run PHP-CS-Fixer
          run: php-cs-fixer fix . --dry-run --diff
  sca:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
        - name: Install composer dependencies
          run: composer install --no-progress --prefer-dist --optimize-autoloader
        - name: Install PHPUnit
          run: vendor/bin/simple-php-unit --version
        - name: Run PHPStan
          run: vendor/bin/phpstan analyse
